version: '2'
services:
    aadharservice-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/aadharService/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=aadharService
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
